# BedrockOnly - Only allows bedrock players on your server!
# Support: https://discord.gg/Scgqfm5EU4
# GitHub Source Code:

# Exempt java players on the kick
exempt-java-players:
  - Notch
  - membercatcousin